version: "3"
services:
  api:
    build: ./API
    environment:
      HOST: 0.0.0.0   # make application accessible from outside the container
      PORT: 3000
    ports:
      - "3001:3000"
    command: npm run dev
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules

volumes:
  api_node_modules: