version: "3"
services:
  bot:
    build: ./Bot
    depends_on:
      database:
        condition: service_healthy
    environment:
      CURRENCY_PAIRS: ${CURRENCY_PAIRS:-BTC-USD}
      FETCH_INTERVAL: ${FETCH_INTERVAL-5}
      OSCILLATION: ${OSCILLATION-0.01}
      RATE: ${RATE-BID}
    ports:
      - "3001:3000"
    command: npm run dev
    volumes:
      - ./bot:/app
      - bot_node_modules:/app/node_modules

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - db:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  bot_node_modules:
  db:
    driver: local