version: "3"
services:
  bot:
    build: ./Bot
    environment:
      CURRENCY_PAIRS: ${CURRENCY_PAIRS:-BTC-USD}
      FETCH_INTERVAL: ${FETCH_INTERVAL-5}
      OSCILLATION: ${OSCILLATION-0.01}
    ports:
      - "3001:3000"
    command: npm run dev
    volumes:
      - ./bot:/app
      - bot_node_modules:/app/node_modules

volumes:
  bot_node_modules: