version: "3"
services:
  bot:
    build: ./Bot
    environment:
      HOST: 0.0.0.0   # make application accessible from outside the container
      PORT: 3000
    ports:
      - "3001:3000"
    command: npm run dev
    volumes:
      - ./bot:/app
      - bot_node_modules:/app/node_modules

volumes:
  bot_node_modules: